export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const FETCH_TASKS = 'FETCH_TASKS'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE'

export const SAVE_TASK = 'SAVE_TASK'
export const SAVE_TASK_SUCCESS = 'SAVE_TASK_SUCCESS'
export const SAVE_TASK_FAILURE = 'SAVE_TASK_FAILURE'

export const UPDATE_TASK = 'UPDATE_TASK'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE'

export const REMOVE_TASK = 'REMOVE_TASK'
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS'
export const REMOVE_TASK_FAILURE = 'REMOVE_TASK_FAILURE'
